apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - port: 9092
    protocol: TCP
    name: client
  externalIPs:
  - 3.86.71.239
  - 3.226.97.57
  - 3.235.197.175
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: rmcdaniel/cloud:kafka
        ports:
        - containerPort: 9092
          name: client
        imagePullPolicy: Always
