apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - port: 9092
    protocol: TCP
    name: external
  - port: 19092
    protocol: TCP
    name: internal
  externalIPs:
  - 54.173.28.73
  - 54.209.249.14
  - 54.80.185.122
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: rmcdaniel/cloud:kafka
        ports:
        - containerPort: 9092
          name: external
        - containerPort: 19092
          name: internal
        imagePullPolicy: Always
