apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 9092
    targetPort: 9092
  selector:
    app: kafka
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/kafka"
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
spec:
  selector:
    matchLabels:
      app: kafka
  minAvailable: 2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: kafka
    name: kafka
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka
    serviceName: kafka-svc
    updateStrategy:
        type: RollingUpdate
    podManagementPolicy: Parallel
    template:
        metadata:
          labels:
            app: kafka
        spec:
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      - labelSelector:
                          matchExpressions:
                            - key: "app"
                              operator: In
                              values:
                              - kafka
                        topologyKey: "kubernetes.io/hostname"
                podAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                     - weight: 1
                       podAffinityTerm:
                         labelSelector:
                            matchExpressions:
                              - key: "app"
                                operator: In
                                values:
                                - zookeeper
                         topologyKey: "kubernetes.io/hostname"
            terminationGracePeriodSeconds: 300
            containers:
            - name: kafka
              image: rmcdaniel/cloud:kafka 
              imagePullPolicy: Always
              ports:
              - containerPort: 9092
                name: client
                protocol: TCP
              volumeMounts:
              - name: datadir
                mountPath: /var/lib/kafka
              readinessProbe:
                tcpSocket:
                  port: 9092
                initialDelaySeconds: 30
                timeoutSeconds: 5
              livenessProbe:
                tcpSocket:
                  port: 9092
                initialDelaySeconds: 30
                timeoutSeconds: 10
    volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi

