apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zookeeper
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/zookeeper"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: zookeeper
    name: zookeeper
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: zookeeper
    serviceName: zookeeper
    updateStrategy:
        type: RollingUpdate
    podManagementPolicy: Parallel
    template:
        metadata:
          labels:
            app: zookeeper
        spec:
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      - labelSelector:
                          matchExpressions:
                            - key: "app"
                              operator: In
                              values:
                              - zookeeper
                        topologyKey: "kubernetes.io/hostname"
            containers:
            - name: zookeeper
              image: rmcdaniel/cloud:zookeeper 
              imagePullPolicy: Always
              ports:
              - containerPort: 2181
                name: client
                protocol: TCP
              - containerPort: 2888
                name: server
                protocol: TCP
              - containerPort: 3888
                name: leader-election
                protocol: TCP
              volumeMounts:
              - name: datadir
                mountPath: /var/lib/zookeeper
              readinessProbe:
                tcpSocket:
                  port: 2181
                initialDelaySeconds: 30
                timeoutSeconds: 5
              livenessProbe:
                tcpSocket:
                  port: 2181
                initialDelaySeconds: 30
                timeoutSeconds: 10
    volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
