apiVersion: v1
kind: Service
metadata:
  name: master
  labels:
    app: master
spec:
  ports:
  - port: 5556
    name: map-master
  - port: 5557
    name: reduce-master
  - port: 5558
    name: up-master
  - port: 5559
    name: map-results
  - port: 5560
    name: reduce-results
  selector:
    app: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  selector:
    matchLabels:
      app: master
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: rlmcdaniel/cloud:master
        env:
        - name: MAP_WORKER_COUNT
          value: "1"
        - name: REDUCE_WORKER_COUNT
          value: "1"
        - name: COUCHDB_USER
          value: "admin"
        - name: COUCHDB_PASSWORD
          value: "password"
        ports:
        - containerPort: 5556
          name: map-master
        - containerPort: 5557
          name: reduce-master
        - containerPort: 5558
          name: up-master
        - containerPort: 5559
          name: map-results
        - containerPort: 5560
          name: reduce-results
        readinessProbe:
          tcpSocket:
            port: 5556
          initialDelaySeconds: 5
          periodSeconds: 10
        imagePullPolicy: Always
