apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    app: couchdb
spec:
  type: NodePort
  ports:
  - port: 5984
    protocol: TCP
    name: external
  selector:
    app: couchdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  selector:
    matchLabels:
      app: couchdb
  replicas: 1
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb
        env:
        - name: COUCHDB_USER
          value: "admin"
        - name: COUCHDB_PASSWORD
          value: "password"
        ports:
        - containerPort: 5984
          name: external
        imagePullPolicy: Always
