apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  type: ClusterIP
  ports:
  - name: internal
    port: 9092
    targetPort: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: broker-0
spec:
  ports:
  - name: external
    port: 9093
    targetPort: 9092
    protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: broker-1
spec:
  ports:
  - name: external
    port: 9093
    targetPort: 9092
    protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: broker-2
spec:
  ports:
  - name: external
    port: 9093
    targetPort: 9092
    protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: kafka-2
  type: NodePort