apiVersion: v1
kind: Service
metadata:
  name: broker-0
spec:
  type: NodePort
  ports:
  - name: internal
    port: 9092
    protocol: TCP
  - name: external
    port: 9093
    protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
---
apiVersion: v1
kind: Service
metadata:
  name: broker-1
spec:
  type: NodePort
  ports:
  - name: internal
    port: 9092
    protocol: TCP
  - name: external
    port: 9093
    protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
---
apiVersion: v1
kind: Service
metadata:
  name: broker-2
spec:
  type: NodePort
  ports:
  - name: internal
    port: 9092
    protocol: TCP
  - name: external
    port: 9093
    protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: kafka-2
