kind: PersistentVolume
apiVersion: v1
metadata:
  name: broker-0
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/kafka"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: broker-1
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/kafka"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: broker-2
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/kafka"
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
spec:
  selector:
    matchLabels:
      app: kafka
  minAvailable: 2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: kafka
    name: kafka
    namespace: default
spec:
    replicas: 3
    selector:
        matchLabels:
            app: kafka
    serviceName: kafka
    updateStrategy:
        type: RollingUpdate
    podManagementPolicy: Parallel
    template:
        metadata:
          labels:
            app: kafka
        spec:
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      - labelSelector:
                          matchExpressions:
                            - key: "app"
                              operator: In
                              values:
                              - kafka
                        topologyKey: "kubernetes.io/hostname"
                podAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                     - weight: 1
                       podAffinityTerm:
                         labelSelector:
                            matchExpressions:
                              - key: "app"
                                operator: In
                                values:
                                - zookeeper
                         topologyKey: "kubernetes.io/hostname"
            terminationGracePeriodSeconds: 300
            containers:
            - name: kafka
              image: rlmcdaniel/cloud:kafka 
              imagePullPolicy: Always
              env:
                - name: KAFKA_SERVICE_PORT_EXTERNAL
                  value: "9093"
                - name: KAFKA_0_SERVICE_HOST
                  value: "3.238.122.116"
                - name: KAFKA_0_SERVICE_PORT
                  value: "31823"
                - name: KAFKA_1_SERVICE_HOST
                  value: "3.238.129.103"
                - name: KAFKA_1_SERVICE_PORT
                  value: "31885"
                - name: KAFKA_2_SERVICE_HOST
                  value: "3.236.146.19"
                - name: KAFKA_2_SERVICE_PORT
                  value: "31948"
              ports:
              - containerPort: 9092
                name: internal
                protocol: TCP
              - containerPort: 9093
                name: external
                protocol: TCP
              volumeMounts:
              - name: datadir
                mountPath: /var/lib/kafka
              readinessProbe:
                tcpSocket:
                  port: 9092
                initialDelaySeconds: 30
                timeoutSeconds: 5
              livenessProbe:
                tcpSocket:
                  port: 9092
                initialDelaySeconds: 30
                timeoutSeconds: 10
    volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
